// code_to_policy_extractor is a dynamic architecture linter: Clean
// Architecture import/naming rules are expressed as Datalog and enforced on
// pull requests — in-process through the supervised SDK path, and as a CI
// gate through the CLI exit-code contract.
//
// CI mode (v0.9 exit-code contract):
//
//	go run . --emit-policy policy.dl        # write the standalone variant
//	mkit eval --policy policy.dl --facts pr.nt --query 'halt(Req, Reason)'
//	# exit 0 = PR clean, exit 1 = policy-deny, 2 = usage error
//
// See ci_gate.sh for the copyable script and TestCIGateExitCodes for the
// executable contract.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	function "github.com/duynguyendang/manglekit/adapters/func"
	"github.com/duynguyendang/manglekit/core"
	"github.com/duynguyendang/manglekit/sdk"
)

// --- Constants: Datalog Policy ---

const archPolicy = `
		% ============================================
		% Clean Architecture Dependency Rules
		% ============================================
		
		% Declare dynamic predicates (will be loaded as facts)
		Decl file_path(File, Layer).
		Decl file_imports(File, ImportLayer).
		Decl file_name_matches(File, Suffix).
		
		% Forbidden: controllers importing domain directly
		halt("Req", "Clean Architecture violation: controller must not import domain directly") :-
			action_operation("Req", "review_pr"),
			file_path(File, "controllers/"),
			file_imports(File, "domain/").
		
		% Forbidden: controllers importing gateways
		halt("Req", "Clean Architecture violation: controller must not import gateways") :-
			action_operation("Req", "review_pr"),
			file_path(File, "controllers/"),
			file_imports(File, "gateways/").
		
		% Forbidden: domain importing any other layer
		halt("Req", "Clean Architecture violation: domain must not import usecases") :-
			action_operation("Req", "review_pr"),
			file_path(File, "domain/"),
			file_imports(File, "usecases/").
		
		halt("Req", "Clean Architecture violation: domain must not import controllers") :-
			action_operation("Req", "review_pr"),
			file_path(File, "domain/"),
			file_imports(File, "controllers/").
		
		halt("Req", "Clean Architecture violation: domain must not import gateways") :-
			action_operation("Req", "review_pr"),
			file_path(File, "domain/"),
			file_imports(File, "gateways/").
		
		% Forbidden: usecases importing controllers
		halt("Req", "Clean Architecture violation: usecases must not import controllers") :-
			action_operation("Req", "review_pr"),
			file_path(File, "usecases/"),
			file_imports(File, "controllers/").
		
		% File naming conventions
		halt("Req", "Naming convention violation: controller files must end with _controller.go") :-
			action_operation("Req", "review_pr"),
			file_path(File, "controllers/"),
			!file_name_matches(File, "_controller.go").
		
		halt("Req", "Naming convention violation: usecase files must end with _usecase.go") :-
			action_operation("Req", "review_pr"),
			file_path(File, "usecases/"),
			!file_name_matches(File, "_usecase.go").
	`

// ciPolicy is the standalone CI variant of archPolicy: same rules, but the
// review context is a local ground fact (not the SDK-injected
// action_operation fact), and the data predicates carry NO Decl — mkit eval
// auto-declares EDB predicates from the --facts graph. Keeping zero overlap
// with std.dl Decls is deliberate: a re-declared predicate fails program
// analysis (verified), so the CI variant must declare nothing std already
// does. Corollary invariant: EVERY predicate a rule references (including
// under negation) must appear in the facts graph too — unseen predicates
// are never declared and the run fails analysis with exit 3, not exit 1.
const ciPolicy = `% ============================================================%
% Generated by code_to_policy_extractor --emit-policy           %
% CI variant of the Clean Architecture policy. See ci_gate.sh.  %
% ============================================================%

review_pr("Req").

halt("Req", "Clean Architecture violation: controller must not import domain directly") :-
    review_pr("Req"), file_path(File, "controllers/"), file_imports(File, "domain/").

halt("Req", "Clean Architecture violation: controller must not import gateways") :-
    review_pr("Req"), file_path(File, "controllers/"), file_imports(File, "gateways/").

halt("Req", "Clean Architecture violation: domain must not import usecases") :-
    review_pr("Req"), file_path(File, "domain/"), file_imports(File, "usecases/").

halt("Req", "Clean Architecture violation: domain must not import controllers") :-
    review_pr("Req"), file_path(File, "domain/"), file_imports(File, "controllers/").

halt("Req", "Clean Architecture violation: domain must not import gateways") :-
    review_pr("Req"), file_path(File, "domain/"), file_imports(File, "gateways/").

halt("Req", "Clean Architecture violation: usecases must not import controllers") :-
    review_pr("Req"), file_path(File, "usecases/"), file_imports(File, "controllers/").

halt("Req", "Naming convention violation: controller files must end with _controller.go") :-
    review_pr("Req"), file_path(File, "controllers/"), !file_name_matches(File, "_controller.go").

halt("Req", "Naming convention violation: usecase files must end with _usecase.go") :-
    review_pr("Req"), file_path(File, "usecases/"), !file_name_matches(File, "_usecase.go").
`

func exampleDir() string {
	_, filename, _, _ := runtime.Caller(0)
	return filepath.Dir(filename)
}

// PRFile represents a file in a pull request with its imports.
type PRFile struct {
	Path         string   `json:"path"`
	Imports      []string `json:"imports"`
	AddedLines   int      `json:"added_lines"`
	DeletedLines int      `json:"deleted_lines"`
}

// PullRequest represents a PR with multiple files.
//
// The `mangle` tags let the supervisor's Zero-Config Reflection flatten the
// payload into facts (e.g. pr_id("Req", "PR-1")) on the supervised path.
// The architecture policy is gated on the `action_operation("Req",
// "review_pr")` fact plus the per-file `file_path`/`file_imports` facts, which
// are loaded as base facts below.
type PullRequest struct {
	PRID   string   `json:"pr_id" mangle:"pr_id"`
	Title  string   `json:"title"`
	Author string   `json:"author" mangle:"author"`
	Files  []PRFile `json:"files"`
}

func main() {
	if len(os.Args) > 2 && os.Args[1] == "--emit-policy" {
		if err := os.WriteFile(os.Args[2], []byte(ciPolicy), 0o600); err != nil {
			log.Fatal(err)
		}
		fmt.Printf("wrote CI policy variant to %s\n", os.Args[2])
		return
	}
	ctx := context.Background()

	fmt.Println("🏗️  Dynamic Architecture Linter")
	fmt.Println("================================")
	fmt.Println("Demonstrating how architecture guidelines are enforced on PRs:")
	fmt.Println("1. Architecture guidelines define allowed dependencies")
	fmt.Println("2. Rules are compiled to Datalog")
	fmt.Println("3. PR dependencies are checked against rules")
	fmt.Println("4. Violations are detected with specific error messages")
	fmt.Println()

	// 1. Initialize Manglekit Client
	client, err := sdk.NewClient(ctx)
	if err != nil {
		log.Fatalf("Failed to initialize client: %v", err)
	}
	defer client.Shutdown(ctx)

	// 2. Load Architecture Rules (simulating LLM extraction from guidelines.md)
	// In production, this would use the extractor to parse architecture_guidelines.md
	fmt.Println("📄 Loading architecture rules...")

	if err := client.Engine().LoadPolicy(ctx, archPolicy); err != nil {
		log.Fatalf("Failed to load architecture policy: %v", err)
	}
	fmt.Println("✅ Loaded architecture rules (7 Clean Architecture rules + 2 naming conventions)")
	fmt.Println()

	// 3. Register the "review_pr" action as a supervised capability.
	//
	// Wrapping it in client.Supervise wires the Zero-Trust Gatekeeper: the
	// pre-check evaluates the architecture policy with the
	// action_operation("Req", "review_pr") fact injected, and the inner
	// function only runs when the policy proceeds. Calling
	// Engine().Assess directly would bypass this and also would NOT inject
	// action_operation, so we drive the action through ExecuteByName.
	reviewAction := function.New("review_pr", func(_ context.Context, pr PullRequest) (string, error) {
		return fmt.Sprintf("reviewed PR %s (%d files)", pr.PRID, len(pr.Files)), nil
	})
	client.RegisterAction("review_pr", client.Supervise(reviewAction))

	// 4. Load Sample PR
	prBytes, err := os.ReadFile(filepath.Join(exampleDir(), "sample_pr.json"))
	if err != nil {
		log.Fatalf("Failed to read sample_pr.json: %v", err)
	}

	var pr PullRequest
	if err := json.Unmarshal(prBytes, &pr); err != nil {
		log.Fatalf("Failed to parse PR: %v", err)
	}

	fmt.Printf("📥 Reviewing PR: %s - %s (by %s)\n", pr.PRID, pr.Title, pr.Author)
	fmt.Printf("   Files changed: %d\n\n", len(pr.Files))

	// 5. Review PR against architecture rules (governed path).
	//
	// The per-file facts are loaded as engine base facts; the supervised
	// pre-check sees them together with action_operation("Req",
	// "review_pr"). Mangle's LoadFacts is additive, so this clean PR must be
	// evaluated BEFORE any violating facts are loaded (see below).
	fmt.Println("🔍 Running architecture lint check...")
	if err := loadPRFacts(ctx, client, pr); err != nil {
		log.Fatalf("Failed to load PR facts: %v", err)
	}
	fmt.Println("📊 Loaded PR facts into policy engine")
	fmt.Println()

	reviewEnv := core.NewEnvelope(pr)
	err = runReview(ctx, client, "review_pr", pr, reviewEnv)
	if core.IsPolicyViolationError(err) {
		fmt.Println("❌ PR REJECTED - Architecture violations found:")
		fmt.Printf("   %v\n", err)
	} else if err != nil {
		log.Fatalf("Review failed unexpectedly: %v", err)
	} else {
		fmt.Println("✅ PR APPROVED - No architecture violations found")
	}

	// 6. Test with a violating PR
	fmt.Println()
	fmt.Println("=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=")
	fmt.Println("🧪 Testing with a VIOLATING PR...")
	fmt.Println("=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=" + "=")
	fmt.Println()

	// Create a violating PR where controller imports domain directly
	violatingPR := PullRequest{
		PRID:   "PR-9999",
		Title:  "Add quick feature (violates architecture)",
		Author: "developer2",
		Files: []PRFile{
			{
				Path:    "controllers/order_controller.go",
				Imports: []string{"usecases/order_usecase", "domain/order"},
			},
			{
				Path:    "usecases/order_usecase.go",
				Imports: []string{"domain/order"},
			},
		},
	}

	fmt.Printf("📥 Reviewing VIOLATING PR: %s - %s\n", violatingPR.PRID, violatingPR.Title)
	fmt.Printf("   Files changed: %d\n\n", len(violatingPR.Files))

	fmt.Println("🔍 Running architecture lint check...")
	if err := loadPRFacts(ctx, client, violatingPR); err != nil {
		log.Fatalf("Failed to load violating PR facts: %v", err)
	}

	violatingEnv := core.NewEnvelope(violatingPR)
	err = runReview(ctx, client, "review_pr", violatingPR, violatingEnv)
	if core.IsPolicyViolationError(err) {
		fmt.Println("❌ PR REJECTED - Architecture violations found:")
		fmt.Printf("   %v\n", err)
	} else if err != nil {
		log.Fatalf("Review failed unexpectedly: %v", err)
	} else {
		fmt.Println("✅ PR APPROVED - No architecture violations found")
	}

	fmt.Println()
	fmt.Println("✅ Dynamic Architecture Linter demonstration complete!")
	fmt.Println()
	fmt.Println("💡 Key Takeaway: Architecture guidelines are automatically enforced.")
	fmt.Println("   Violations are caught before code is merged, with specific error")
	fmt.Println("   messages indicating which rule was violated and in which file.")
}

// runReview drives the review_pr action through the supervised path. The
// inner function only executes when the pre-check proceeds; on a Tier-0/1
// violation the supervisor returns a core.PolicyViolationError and the
// action is blocked.
func runReview(ctx context.Context, client *sdk.Client, name string, payload any, _ core.Envelope) error {
	_, err := client.ExecuteByName(ctx, name, payload)
	return err
}

// loadPRFacts converts a PR's files into Datalog facts and loads them as
// engine base facts. These are the facts the architecture policy is gated on.
func loadPRFacts(ctx context.Context, client *sdk.Client, pr PullRequest) error {
	var facts []string
	for _, file := range pr.Files {
		facts = append(facts, fmt.Sprintf(`file_path("%s", "%s")`, file.Path, getLayer(file.Path)))
		for _, imp := range file.Imports {
			facts = append(facts, fmt.Sprintf(`file_imports("%s", "%s")`, file.Path, getLayer(imp)))
		}
		if hasValidName(file.Path) {
			facts = append(facts, fmt.Sprintf(`file_name_matches("%s", "%s")`, file.Path, getSuffix(file.Path)))
		}
	}
	return client.LoadFacts(ctx, facts)
}

// getLayer extracts the layer prefix from a file path.
func getLayer(path string) string {
	switch {
	case len(path) >= 11 && path[:11] == "controllers":
		return "controllers/"
	case len(path) >= 8 && path[:8] == "usecases":
		return "usecases/"
	case len(path) >= 6 && path[:6] == "domain":
		return "domain/"
	case len(path) >= 8 && path[:8] == "gateways":
		return "gateways/"
	default:
		return "unknown"
	}
}

// hasValidName checks if a file follows naming conventions.
func hasValidName(path string) bool {
	switch getLayer(path) {
	case "controllers/":
		return strings.HasSuffix(path, "_controller.go")
	case "usecases/":
		return strings.HasSuffix(path, "_usecase.go")
	default:
		return true
	}
}

// getSuffix returns the naming convention suffix.
func getSuffix(path string) string {
	layer := getLayer(path)
	switch layer {
	case "controllers/":
		return "_controller.go"
	case "usecases/":
		return "_usecase.go"
	default:
		return ""
	}
}
